# Template workflow for OpenShift GitHub Connector

name: CRDA Scan

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - edited

jobs:
  crda-scan:
    name: CRDA Scan
    runs-on: ubuntu-20.04

    steps:
      # May replace with setup-[go|java|node|python]
      - uses: setup-node@v2

      - name: Install CRDA
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: github
          github_pat: ${{ github.token }}
          crda: latest

      - name: CRDA Scan
        # TODO - v1
        uses: redhat-actions/crda@main
        with:
          crda_key: ${{ secrets.CRDA_KEY }}
          manifest_directory: .
          # snyk_token: ${{ secrets.SNYK_TOKEN }}
          # manifest_directory: ""
