# Template workflow for OpenShift GitHub Connector

name: Scan with CodeReady Dependency Analytics

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - edited
jobs:
  crda-scan:
    name: Scan with CodeReady Dependency Analytics
    runs-on: ubuntu-20.04

    steps:

      # May use setup-[go|java|node|python]
      - uses: setup-node@v2
      - name: Install CRDA
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: github
          github_pat: ${{ github.token }}
          crda: latest
        # https://github.com/redhat-actions/crda/
      - name: CRDA Scan
        # TODO - v1
        uses: redhat-actions/crda@main
        with:
          crda_key: ${{ secrets.CRDA_KEY }}
