name: CRDA scan
on:
  push:
  workflow_dispatch:
  pull_request_target:
    types: [ assigned, opened, synchronize, reopened, labeled, edited ]
jobs:
  test:
    runs-on: ubuntu-20.04
    name: Analyse Node project
    env:
      MVN_REPO_DIR: ~/.m2/repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install CRDA
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: github
          github_pat: ${{ github.token }}
          crda: "latest"

      - name: CRDA Scan
        id: scan
        # uses: redhat-actions/crda@main
        uses: tetchel/crda@fix-39
        with:
          crda_key: ${{ secrets.CRDA_KEY }}
          fail_on: never

      - name: Echo Report Link
        run: echo ${{ steps.scan.outputs.report_link }}

      - name: Save intermediate files
        if: ${{ steps.scan.outputs.crda_report_json && steps.scan.outputs.crda_report_sarif }}
        run: |
          mkdir -p uploads
          mv ${{ steps.scan.outputs.crda_report_json }} uploads
          mv ${{ steps.scan.outputs.crda_report_sarif }} uploads

      - name: Upload merged Results
        uses: actions/upload-artifact@v2
        with:
          name: workfiles
          path: ./uploads
